### PR TITLE
Travis: Use clang 10 for static analysis 

### PR DESCRIPTION
**Pull request by Wenzel**
* add `SCAN_BUILD` cmake var to configure `scan-build` binary used for static analysis
on Ubuntu, multiple version of the `clang-tools` package are available:
- `clang-tools`
- `clang-tools-6`
- `clang-tools-7`
- etc..

this variable allow to control which `scan-build` binary will be used.

* update static analysis in Travis to use `clang-tools-7`

### CODE REVIEW

**Comment by tklengyel** [comment]
Isn't clang 7 the default already?

**Comment by Wenzel** [comment]
I believe that clang 6 is the default:
https://packages.ubuntu.com/bionic/devel/clang-tools

However, we can go up to `clang-tools-10`:
https://packages.ubuntu.com/bionic/clang-tools-10

But It spotted small issues in the Xen driver that I wasn't sure how to solve.
I haven't had a deep look though.

**Comment by Wenzel** [comment]
I updated the PR to use `clang-tools-10` and fixed the issues raised in the Xen driver.

**Comment by mtarral** [comment]
I don't understand why Travis refuses to trigger a new build

**Comment by tklengyel** [comment]
I don't see any error on the Travis side either.

**Comment by Wenzel** [comment]
I added a comment just to change the commit and to be able to push --force.
Travis works now :man_shrugging: :man_shrugging: :man_shrugging:

**Pull request merged**
