### PR TITLE
cmake: disable testing by default

### LINKED ISSUE #745: Enable check build dependency only when testing is enabled
related to #744 

Testing option is enabled by default:
https://github.com/libvmi/libvmi/blob/master/CMakeLists.txt#L56

check is added here as a dependency:
https://github.com/libvmi/libvmi/blob/master/tests/CMakeLists.txt#L1

The fix should be to disable testing by default.
What do you think @tklengyel ?

### PR DESCRIPTION
**Pull request by Wenzel**
fixes #745

### CODE REVIEW

**Comment by tklengyel** [comment]
Why are you removing check from travis?

**Comment by Wenzel** [comment]
Because check becomes an optional dependency and is not needed anymore to build libvmi.
We are only using make test in Jenkins.

**Comment by Wenzel** [comment]
As you wish, i updated the PR

**Comment by Wenzel** [comment]
@tklengyel all green

**Pull request merged**
