### PR TITLE
Added patch for qemu version 2.12

### PR DESCRIPTION
**Pull request by buekera**
I created a little diff file which contains necessary changes to qemu to enable fast memory acces for libvmi.

### CODE REVIEW

**Comment by buekera** [comment]
The checks from Travis are failing due to some whitespace characters. This can be ignored as this is just a patch file in my opinion.

**Comment by tklengyel** [comment]
@buekera yes, the whitespace check on this can be ignored
@Wenzel can you take a look at this?

**Comment by Wenzel** [comment]
@buekera has the `2.12` been released yet ?
the last tag i can see on https://github.com/qemu/qemu/tree/v2.12.0-rc3 is `v2.12.0-rc3`

**Comment by Wenzel** [comment]
What happened to `docs/qmp-commands.txt` ?
https://github.com/libvmi/libvmi/blob/master/tools/qemu-kvm-patch/kvm-qemu-v2.8-libvmi.patch#L37

**Comment by Wenzel** [comment]
The `process-list.py` example works for me:
~~~
~~~

**Comment by buekera** [comment]
No, qemu 2.12 is not released yet, sorry for writing down the wrong version, it's `2.12.0-rc3` as you already stated correctly. This patch should also work for `2.11`. I also believe that it will work for the stable release of `2.12` but we have to wait for it of course.

I totally forgot about the `docs/qmp-commands.txt`. Should I add it to the patch file for the sake of completeness or can I just ignore it because it won't impair the functionality of qemu?

**Comment by Wenzel** [comment]
> No, qemu 2.12 is not released yet, sorry for writing down the wrong version, it's 2.12.0-rc3 as you already stated correctly. This patch should also work for 2.11. I also believe that it will work for the stable release of 2.12 but we have to wait for it of course.

I would prefer to wait for the release of the stable `2.12` to be sure.

> I totally forgot about the docs/qmp-commands.txt. Should I add it to the patch file for the sake of completeness or can I just ignore it because it won't impair the functionality of qemu?

No, this file has been removed between `2.8` and `2.12`, there is no need to worry about it.

**Comment by buekera** [comment]
> I would prefer to wait for the release of the stable 2.12 to be sure.
I'm fine with that. Would you mind trying to patch `2.11` with this file? I would do it myself but I'm not on my computers for a few days. When this is indeed working with `2.11`  we could release it now. I don't know if it's worth the trouble tough, as I'm not sure how many people are "waiting" for this patch.

**Comment by Wenzel** [comment]
QEMU `2.12.0` has been released.
I will compile it and test the patch next week.

**Comment by Wenzel** [comment]
I'm testing the patch right now, and with the `vmi-process-list` example, libvmi initialization hangs:
~~~
$ ./examples/vmi-process-list Windows_7_x64
xencall: error: Could not obtain handle on privileged command interface: No such file or directory
VMI_ERROR: Failed to open libxc interface.
Failed to find a suitable xenctrl.so!
--found KVM
LibVMI Version 0.13.0
LibVMI Driver Mode 1
--completed driver init.
--got id from name (Windows_7_x64 --> 4)
**set image_type = Windows_7_x64
--libvirt version 4000000
--qmp: virsh -c qemu:///system qemu-monitor-command Windows_7_x64 '{"execute": "pmemaccess", "arguments": {"path": "/tmp/vmip7ffVx"}}'
--kvm: using custom patch for fast memory access
--qmp: virsh -c qemu:///system qemu-monitor-command Windows_7_x64 '{"execute": "human-monitor-command", "arguments": {"command-line": "info mtree"}}'
**set allocated_ram_size = 80000000, max_physical_address = 0x80000000
--qmp: virsh -c qemu:///system qemu-monitor-command Windows_7_x64 '{"execute": "human-monitor-command", "arguments": {"command-line": "info registers"}}'
--qmp: virsh -c qemu:///system qemu-monitor-command Windows_7_x64 '{"execute": "human-monitor-command", "arguments": {"command-line": "info registers"}}'
**set pae = 1
**set pse = 1
--qmp: virsh -c qemu:///system qemu-monitor-command Windows_7_x64 '{"execute": "human-monitor-command", "arguments": {"command-line": "info registers"}}'
**set lme = 1
--qmp: virsh -c qemu:///system qemu-monitor-command Windows_7_x64 '{"execute": "human-monitor-command", "arguments": {"command-line": "info registers"}}'
**IA-32e paging
**sanity checking cr3 = 0x0000000000187000
--looking for config file at /home/tarrma/fsecure/libvmi/libvmi.conf
--looking for config file at /home/tarrma/etc/libvmi.conf
--looking for config file at /etc/libvmi.conf
**Using config file at /etc/libvmi.conf
**set os_type to Windows.
--qmp: virsh -c qemu:///system qemu-monitor-command Windows_7_x64 '{"execute": "human-monitor-command", "arguments": {"command-line": "info registers"}}'
**Attempting KdDebuggerDataBlock search methods
**Trying find_kdbg_address_instant
**Trying find_kdbg_address_faster
--qmp: virsh -c qemu:///system qemu-monitor-command Windows_7_x64 '{"execute": "human-monitor-command", "arguments": {"command-line": "info registers"}}'
--qmp: virsh -c qemu:///system qemu-monitor-command Windows_7_x64 '{"execute": "human-monitor-command", "arguments": {"command-line": "info registers"}}'
--PTLookup: lookup vaddr = 0xfffff80002a0cd00
--PTLookup: dtb = 0x0000000000187000
--MEMORY cache set 0x187000
~~~

**Comment by Wenzel** [comment]
If somone else could test and reproduce these results, it would be helpful.
thanks.

**Comment by buekera** [comment]
@Wenzel I will test it when I get home tonight.

**Comment by Wenzel** [comment]
@buekera did you find some time to test the patch ?

**Comment by Wenzel** [comment]
I believe we can close this one, since https://github.com/libvmi/libvmi/pull/821 is merged.

**Pull request closed without merging**
