### PR TITLE
added a npyscreen/configobj based python configuration editor

### PR DESCRIPTION
**Pull request by dalevy**
This python application uses npyscreen/configobj to create libvmi config files. The user can add as many configurations for Windows/Linux as they want to the applications "running config" then choose to write the file or edit the file when ready. The application includes signal handling for SIGINT as well as a lot of error checking for erroneous input and failed options. My only concern is that it requires install of nypscreen and configobj. I'm not sure if that is okay or should be somehow included with the application. Development repo is here https://github.com/dalevy/python-libvmi-config-editor

### CODE REVIEW

**Comment by tklengyel** [comment]
Thanks fot adding this. Requiring extra packages for tools is fine. However, going forward in the future we might want to think about deprecating the config value based init and only use the Rekall profiles. It is arguably a cleaner and more flexible approach to getting the magic values.

**Comment by dalevy** [comment]
I'm going to do a little research on initializing libvmi with Rekall - sounds interesting. I imagine it would require figuring out what kernel version the vm is running for windows/linux respectively. I'm going to dig through the init function and see if I can make it happen.

**Comment by dalevy** [comment]
Is there any feedback on this PR?

**Comment by awsaba** [comment]
Please include the following the usage information somewhere, either in the header comment or a short readme:

- Python versions supported
- Python package and any other dependencies

**Comment by dalevy** [comment]
I will make the changes and a few others and then resubmit.

**Comment by dalevy** [comment]
UPDATE: I have included a README file that specifies dependencies and the python versioning as well as added that to the top of the .py file. I tested with (2.7.5-2.7.6). My assumption is that it works for Python >= 2.7. Although, I plant to try different environments once I get "tox" working. Also, I'm not sure if I did the commit changes write via a push to my master fork...I tried rebasing but it said everything was up to date. Please let me know if I'm going about this wrong as I don't want to pollute libvmi's project history..

-Thanks.

**Comment by dalevy** [comment]
Could I please have some feedback on this PR? Also, I did identify a minor issue but I'm not sure whether to fix and resubmit since it has been quite some time.

**Comment by tklengyel** [comment]
No need to resubmit it as a new PR, just squash the commits in this branch into a single and and do a push with --force. It will update this PR.

**Comment by dalevy** [comment]
PR Updated.

**Comment by awsaba** [comment]
@dalevy I think we are just waiting for the commits to be squashed before merging this PR.

**Comment by tklengyel** [comment]
@smaresca @awsaba: I think we might want to start using the github squash and merge function. It makes the network graph flattened but otherwise it might be an easier method for people submitting PRs.

**Comment by dalevy** [comment]
@awsaba Is there something I should do to squash the commits?

**Comment by tklengyel** [comment]
@dalevy: You have 3 commits in this branch right now. You can squash the last two commits into the first one if you do `git rebase -i HEAD~3` and mark the last two commits as "fix". Afterwards, you need to do a `git push origin master --force` to update this PR (provided you named your repository origin, you can check with `git remote -v` to verify).

**Comment by dalevy** [comment]
I will fix this and check some things before I push also...

I would like to apologize for the strange fact that I'm listed as both dalevy and dlevy022 as well... I am doing senior design at school right now and they mandated we use our (username) username@fiu.edu and school email to submit our work and thus I had to create another account for my school work while switching my personal github (the one for this PR) account to a different email - academic bureaucracy.

**Comment by smaresca** [comment]
@dalevy not a problem! Thanks for contributing this

**Pull request merged**
