### PR TITLE
Xen 4.11 support

### PR DESCRIPTION
**Pull request by tklengyel**

### CODE REVIEW

**Comment by smaresca** [comment]
xc: error: Failed to enable vm_event
 (16 = Device or resource busy): Internal error
VMI_ERROR: vm_event is (or was) active on this domain

**Comment by tklengyel** [comment]
Yea, I'm trying to figure out what is causing that cause that usually happens when something didn't exit cleanly.

**Comment by tklengyel** [comment]
Running the same script Jenkins does manually works just fine. @libvmi-jenkins Retest this please.

**Comment by tklengyel** [comment]
Restarting Jenkins made the error go away `¯\_(ツ)_/¯`

**Comment by smaresca** [comment]
@libvmi-jenkins Retest this please.

**Pull request merged**
