### PR TITLE
Fix KASLR offset bug for x86_64

### PR DESCRIPTION
**Pull request by richarduu**
When the kernel version is 4.13.0+, the previous kaslr lookup function
fails somehow.

Determining KASLR offset in x86_64 can be done in a simpler way following
the official kernel address layout documentation:
    https://www.kernel.org/doc/Documentation/x86/x86_64/mm.txt

What we need to do is just keep attemping to get the k2p mapping of the first
page mapped in kernel text mapping. We can get the offset once we get the first
kernel text page mapped. Because in the range of 0xffffffff80000000 ~
0xffffffffa0000000 there is only kernel text, and the first page found mapped
beginning from 0xffffffff81000000 is the start of the kernel text mapping, thus
we can get the kaslr offset.

Note that here it should be 0xffffffff81000000 instead of 0xffffffff80000000.

Also, kernel text is by default using 2M huge page so we are adding 0x200000
instead of 0x1000.

Tested on x86_64 Ubuntu 16.04 with kernel v4.4.0 and v4.15.0.

### CODE REVIEW

**Comment by richarduu** [comment]
One check failed because of a `{` placed at the same line with the function name... 
Should I cancel it and create another pull request, or just ignore it?

```
-status_t get_kaslr_offset_ia32e(vmi_instance_t vmi){
+status_t get_kaslr_offset_ia32e(vmi_instance_t vmi)
+{
```

**Comment by smaresca** [comment]
@richarduu no need to create another pull request, just make the modification, commit, squash/fixup down to one commit + push

**Comment by richarduu** [comment]
Thanks @smaresca , it is squashed, and passed.

**Comment by tklengyel** [comment]
@libvmi-jenkins This is OK to test.

**Comment by tklengyel** [comment]
Looks good, thanks!

**Pull request merged**
