### PR TITLE
Atomic register retrieval for process_list example to work

### PR DESCRIPTION
**Pull request by nystilaps**
Atomic register retrieval for process_list example to work

### CODE REVIEW

**Comment by nystilaps** [comment]
How is it going?

**Comment by tklengyel** [comment]
@libvmi-jenkins This is OK to test.

**Comment by tklengyel** [comment]
A bit more information would be useful for why this patch is needed.

**Comment by disaykin** [comment]
If you read the gs_base and gs_shadow registers values ​​not at the same time, swapgs operation can occur between these reads. In the DRAKVUF project the libvmi library is initialized on a paused VM. And we can probe the values from gs_base and gs_shadow registers as KPCR.
If we try initialize libvmi on running VM, we can receive TEB address in both registers.

**Comment by tklengyel** [comment]
So the correct solution to that problem would be to update `x86_registers_t` to include the register you need when you run `vmi_get_vcpuregs`. Updating the Xen interface that transmits the register snapshot for each event could also be updated.

**Comment by nystilaps** [comment]
@tklengyel I don't understand what I should do.
Could you please explain, which functions should I update further?

**Comment by nystilaps** [comment]
I use program "process_list" from libvmi examples.
It doesn't work without this patch because it doesn't pause the VM.

**Comment by nystilaps** [comment]
It probably pauses VM _after_ getting KPCR.

I have posted log in https://github.com/libvmi/libvmi/issues/442
I copied log here, note changing RIP:
** (vmi->page_mode == VMI_PM_IA32E) Entering KPCR register selection loop...
** (vmi->page_mode == VMI_PM_IA32E) => Using kpcr_register_to_use=GS_BASE.
**Trying to init from Rekall profile
** Trying kpcr_register_to_use to get KPCR.
**Error while init from Rekall profile. Getting KPCR from user mode or just after syscall before 'swapgs'.
**vCPU0 doesn't seem to have KiInitialPCR mapped, can't init from Rekall profile. Kpcr=0x7fffff94000, kpcr_rva=0x1f2d00
**vCPU0 RIP=0x7fefd6681af
** Trying GS_BASE failed.
** (vmi->page_mode == VMI_PM_IA32E) => Using kpcr_register_to_use=SHADOW_GS.
**Trying to init from Rekall profile
** Trying kpcr_register_to_use to get KPCR.
**Error while init from Rekall profile. Getting KPCR from user mode or just after syscall before 'swapgs'.
**vCPU0 doesn't seem to have KiInitialPCR mapped, can't init from Rekall profile. Kpcr=0x7fffff5e000, kpcr_rva=0x1f2d00
**vCPU0 RIP=0xfffff800029a5357
** Trying SHADOW_GS failed.
** (vmi->page_mode == VMI_PM_IA32E) => Using kpcr_register_to_use=MSR_SHADOW_GS_BASE.
**Trying to init from Rekall profile
** Trying kpcr_register_to_use to get KPCR.
** driver_get_vcpureg(..) failed.
** Trying MSR_SHADOW_GS_BASE failed.
** (vmi->page_mode == VMI_PM_IA32E) => Using kpcr_register_to_use=FS_BASE.
**Trying to init from Rekall profile
** Trying kpcr_register_to_use to get KPCR.
**Error while init from Rekall profile. Getting KPCR from user mode or just after syscall before 'swapgs'.
**vCPU0 doesn't seem to have KiInitialPCR mapped, can't init from Rekall profile. Kpcr=0xfff9e000, kpcr_rva=0x1f2d00
**vCPU0 RIP=0xfffff880033de9c2
** Trying FS_BASE failed.
** (vmi->page_mode == VMI_PM_IA32E) => Using kpcr_register_to_use.
**Trying to init from Rekall profile
** Trying kpcr_register_to_use to get KPCR.
** driver_get_vcpureg(..) failed.
** Trying failed.

**Comment by tklengyel** [comment]
So then why isn't the fix simply to pause the VM until the initialization completes?

**Comment by nystilaps** [comment]
At the time of writing the fix I was not sure what and where is wrong.
It isn't (jet) obvious for me how to stop VM using only libvmi at the right time.
Probably it would be a better fix.

**Comment by tklengyel** [comment]
That's alright, that's why its important to have these discussions, so that we come up with the right solution to the problem. The PR as is doesn't seem to be that. I would open a separate issue that documents the problem, and do a new PR that pauses thw VM during init.

**Comment by nystilaps** [comment]
Ok, great!
Thank you for the discussion.

**Pull request closed without merging**
