### PR TITLE
Bareflank driver

### PR DESCRIPTION
**Pull request by tklengyel**
This PR adds support to the [Bareflank hypervisor](https://bareflank.github.io/hypervisor) when running it with the [LibVMI extensions](https://github.com/libvmi/bareflank_libvmi_extension).

The Bareflank driver is unique in that it provides host-introspection instead of VM-introspection. That is, the hypervisor provides access to raw physical memory to the actual system the LibVMI applications is running on by performing EPT-remapping of physical memory. The hypervisor also provides access to the vCPU registers through a shared-memory buffer formatted in JSON. The presence of the hypervisor is detected through `CPUID` when querying the leaf `1337` to which the hypervisor responds with `42` in all CPUID leafs.

It is important to note that the Bareflank hypervisor does not sanity check accesses to physical memory. Running some examples (for example `vmi-dump-memory`) may be dangerous and crash the system, for example when accessing MMIO regions. To avoid that a new API is added that allows one to specify the memory map of the target system so that LibVMI won't access invalid ranges.

This PR is loosely based on @boddumanohar Google Summer of Code 2018 project

Here is an example output running on my laptop with Ubuntu 18.04 desktop. Notice how the actual vmi application shows up in the list:
```
~/workspace/libvmi$ ./examples/vmi-process-list host
Process listing for VM (null) (id=0)
[    0] swapper/0 (struct addr:ffffffff9e212480)
[    1] systemd (struct addr:ffff9293a45a9740)
[    2] kthreadd (struct addr:ffff9293a45a8000)
[    4] kworker/0:0H (struct addr:ffff9293a45ac5c0)
[    6] mm_percpu_wq (struct addr:ffff9293a45e2e80)
[    7] ksoftirqd/0 (struct addr:ffff9293a45e45c0)
[    8] rcu_sched (struct addr:ffff9293a45e5d00)
[    9] rcu_bh (struct addr:ffff9293a45e1740)
[   10] migration/0 (struct addr:ffff9293a45e0000)
[   11] watchdog/0 (struct addr:ffff9293a45f5d00)
[   12] cpuhp/0 (struct addr:ffff9293a4619740)
[   13] cpuhp/1 (struct addr:ffff9293a4618000)
[   14] watchdog/1 (struct addr:ffff9293a4649740)
[   15] migration/1 (struct addr:ffff9293a4648000)
[   16] ksoftirqd/1 (struct addr:ffff9293a464ae80)
[   18] kworker/1:0H (struct addr:ffff9293a464dd00)
[   19] cpuhp/2 (struct addr:ffff9293a47a0000)
[   20] watchdog/2 (struct addr:ffff9293a47a2e80)
[   21] migration/2 (struct addr:ffff9293a47a45c0)
[   22] ksoftirqd/2 (struct addr:ffff9293a47a5d00)
[   24] kworker/2:0H (struct addr:ffff9293a47aae80)
[   25] cpuhp/3 (struct addr:ffff9293a47ac5c0)
[   26] watchdog/3 (struct addr:ffff9293a47add00)
[   27] migration/3 (struct addr:ffff9293a47a9740)
[   28] ksoftirqd/3 (struct addr:ffff9293a47a8000)
[   30] kworker/3:0H (struct addr:ffff9293a401c5c0)
[   31] cpuhp/4 (struct addr:ffff9293a401dd00)
[   32] watchdog/4 (struct addr:ffff9293a4019740)
[   33] migration/4 (struct addr:ffff9293a4018000)
[   34] ksoftirqd/4 (struct addr:ffff9293a4072e80)
[   36] kworker/4:0H (struct addr:ffff9293a4075d00)
[   37] cpuhp/5 (struct addr:ffff9293a4071740)
[   38] watchdog/5 (struct addr:ffff9293a4070000)
[   39] migration/5 (struct addr:ffff9293a40c8000)
[   40] ksoftirqd/5 (struct addr:ffff9293a40cae80)
[   42] kworker/5:0H (struct addr:ffff9293a40cdd00)
[   43] cpuhp/6 (struct addr:ffff9293a40c9740)
[   44] watchdog/6 (struct addr:ffff9293a4120000)
[   45] migration/6 (struct addr:ffff9293a4122e80)
[   46] ksoftirqd/6 (struct addr:ffff9293a41245c0)
[   48] kworker/6:0H (struct addr:ffff9293a4121740)
[   49] cpuhp/7 (struct addr:ffff9293a4178000)
[   50] watchdog/7 (struct addr:ffff9293a417ae80)
[   51] migration/7 (struct addr:ffff9293a417c5c0)
[   52] ksoftirqd/7 (struct addr:ffff9293a417dd00)
[   54] kworker/7:0H (struct addr:ffff9293a41a45c0)
[   55] kdevtmpfs (struct addr:ffff9293a41f5d00)
[   56] netns (struct addr:ffff9293a4268000)
[   57] rcu_tasks_kthre (struct addr:ffff9293a426ae80)
[   58] kauditd (struct addr:ffff9293a426c5c0)
[   61] khungtaskd (struct addr:ffff9293a4348000)
[   62] oom_reaper (struct addr:ffff9293a4352e80)
[   63] writeback (struct addr:ffff9293a43545c0)
[   64] kcompactd0 (struct addr:ffff9293a4355d00)
[   65] ksmd (struct addr:ffff9293a436ae80)
[   66] khugepaged (struct addr:ffff9293a436c5c0)
[   67] crypto (struct addr:ffff9293a436dd00)
[   68] kintegrityd (struct addr:ffff9293a4369740)
[   69] kblockd (struct addr:ffff9293a4368000)
[   76] ata_sff (struct addr:ffff9293a41a0000)
[   77] md (struct addr:ffff9293a41a2e80)
[   78] edac-poller (struct addr:ffff9293a3e4dd00)
[   79] devfreq_wq (struct addr:ffff9293a3e49740)
[   81] watchdogd (struct addr:ffff9293a3e4ae80)
[   85] kswapd0 (struct addr:ffff9293a266c5c0)
[   86] ecryptfs-kthrea (struct addr:ffff9293a266dd00)
[  128] kthrotld (struct addr:ffff929399660000)
[  129] acpi_thermal_pm (struct addr:ffff929399662e80)
[  134] ipv6_addrconf (struct addr:ffff9293a4349740)
[  143] kstrp (struct addr:ffff929399622e80)
[  160] charger_manager (struct addr:ffff929399605d00)
[  217] scsi_eh_0 (struct addr:ffff9293a43ec5c0)
[  218] scsi_tmf_0 (struct addr:ffff9293a43edd00)
[  219] scsi_eh_1 (struct addr:ffff9293a43eae80)
[  220] scsi_tmf_1 (struct addr:ffff92939805dd00)
[  221] scsi_eh_2 (struct addr:ffff929398059740)
[  222] scsi_tmf_2 (struct addr:ffff929398058000)
[  224] kworker/u17:0 (struct addr:ffff929399632e80)
[  225] i915/signal:0 (struct addr:ffff9293996345c0)
[  226] i915/signal:1 (struct addr:ffff929399635d00)
[  227] i915/signal:2 (struct addr:ffff929399655d00)
[  228] i915/signal:4 (struct addr:ffff929399651740)
[  230] kworker/2:1H (struct addr:ffff929399650000)
[  261] jbd2/sda5-8 (struct addr:ffff92939805c5c0)
[  262] ext4-rsv-conver (struct addr:ffff9293984a2e80)
[  306] systemd-journal (struct addr:ffff92939962ae80)
[  327] kworker/3:1H (struct addr:ffff9293a4351740)
[  333] lvmetad (struct addr:ffff92939eb62e80)
[  337] kworker/7:1H (struct addr:ffff92939eb61740)
[  338] kworker/1:1H (struct addr:ffff92939eb60000)
[  339] systemd-udevd (struct addr:ffff9293a3208000)
[  341] loop0 (struct addr:ffff929399631740)
[  370] kworker/4:1H (struct addr:ffff9293a3c8dd00)
[  371] loop1 (struct addr:ffff9293a3c89740)
[  375] loop2 (struct addr:ffff9293a3c08000)
[  376] loop3 (struct addr:ffff9293a3c09740)
[  379] loop4 (struct addr:ffff929397512e80)
[  380] kworker/0:1H (struct addr:ffff9293a320ae80)
[  385] loop5 (struct addr:ffff92939962c5c0)
[  386] kworker/5:1H (struct addr:ffff9293a3c0ae80)
[  387] loop6 (struct addr:ffff92939898ae80)
[  388] loop7 (struct addr:ffff9293a3c88000)
[  389] loop8 (struct addr:ffff9293a3c8c5c0)
[  390] loop9 (struct addr:ffff9293a43c0000)
[  391] kworker/6:1H (struct addr:ffff9293a3c0dd00)
[  392] loop10 (struct addr:ffff929399628000)
[  393] loop11 (struct addr:ffff929399629740)
[  398] loop12 (struct addr:ffff9293975145c0)
[  424] kworker/u17:2 (struct addr:ffff92939e515d00)
[  543] irq/51-DELL081B (struct addr:ffff92939965ae80)
[  607] kmemstick (struct addr:ffff9293a320dd00)
[  612] cfg80211 (struct addr:ffff92939858dd00)
[  617] irq/131-iwlwifi (struct addr:ffff92939965dd00)
[  700] systemd-timesyn (struct addr:ffff9293a09a0000)
[  704] systemd-resolve (struct addr:ffff9293a09a45c0)
[  797] cron (struct addr:ffff9293a2de8000)
[  798] rsyslogd (struct addr:ffff9293a2dec5c0)
[  800] dbus-daemon (struct addr:ffff92939898c5c0)
[  806] networkd-dispat (struct addr:ffff9293a3209740)
[  807] udisksd (struct addr:ffff9293996545c0)
[  808] avahi-daemon (struct addr:ffff929399600000)
[  812] ModemManager (struct addr:ffff92939e695d00)
[  814] systemd-logind (struct addr:ffff92939e6945c0)
[  817] thermald (struct addr:ffff92939e690000)
[  818] NetworkManager (struct addr:ffff9293a41f0000)
[  820] avahi-daemon (struct addr:ffff92939852c5c0)
[  822] acpid (struct addr:ffff9293a41f45c0)
[  824] snapd (struct addr:ffff9293a2de9740)
[  825] irqbalance (struct addr:ffff929398a65d00)
[  855] accounts-daemon (struct addr:ffff9293a06b0000)
[  856] bluetoothd (struct addr:ffff9293a06b5d00)
[  857] wpa_supplicant (struct addr:ffff929398fcc5c0)
[  866] kerneloops (struct addr:ffff929399621740)
[  870] kerneloops (struct addr:ffff9293a0602e80)
[  887] polkitd (struct addr:ffff9293a06b2e80)
[  928] unattended-upgr (struct addr:ffff9293a266ae80)
[  930] libvirtd (struct addr:ffff929398fc9740)
[  937] gdm3 (struct addr:ffff92939b038000)
[  952] gdm-session-wor (struct addr:ffff9293a32cdd00)
[  979] systemd (struct addr:ffff92939e622e80)
[  980] (sd-pam) (struct addr:ffff9293a41f2e80)
[  991] gdm-wayland-ses (struct addr:ffff9293a25c45c0)
[  993] dbus-daemon (struct addr:ffff9293a0605d00)
[  995] gnome-session-b (struct addr:ffff9293a25c0000)
[ 1012] gnome-shell (struct addr:ffff92939a2745c0)
[ 1037] upowerd (struct addr:ffff9293a25c2e80)
[ 1075] Xwayland (struct addr:ffff9293a27add00)
[ 1094] at-spi-bus-laun (struct addr:ffff92939c005d00)
[ 1099] dbus-daemon (struct addr:ffff92939d9c1740)
[ 1101] at-spi2-registr (struct addr:ffff929397f91740)
[ 1107] pulseaudio (struct addr:ffff929397511740)
[ 1108] rtkit-daemon (struct addr:ffff929397f92e80)
[ 1225] dnsmasq (struct addr:ffff92939a36dd00)
[ 1226] dnsmasq (struct addr:ffff92939d1c45c0)
[ 1254] ibus-daemon (struct addr:ffff92939c9c45c0)
[ 1257] ibus-dconf (struct addr:ffff92939d0a9740)
[ 1259] ibus-x11 (struct addr:ffff92939d131740)
[ 1262] ibus-portal (struct addr:ffff92939d0aae80)
[ 1275] boltd (struct addr:ffff9293a09a1740)
[ 1276] packagekitd (struct addr:ffff92939d1bae80)
[ 1277] gsd-xsettings (struct addr:ffff92939d1b8000)
[ 1282] gsd-a11y-settin (struct addr:ffff92939d1bdd00)
[ 1284] gsd-clipboard (struct addr:ffff92939d1bc5c0)
[ 1286] gsd-color (struct addr:ffff929396f40000)
[ 1288] gsd-datetime (struct addr:ffff929396f42e80)
[ 1290] gsd-housekeepin (struct addr:ffff929396f45d00)
[ 1291] gsd-keyboard (struct addr:ffff92939c819740)
[ 1294] gsd-media-keys (struct addr:ffff929396f445c0)
[ 1296] gsd-mouse (struct addr:ffff929396f41740)
[ 1300] gsd-power (struct addr:ffff92939d0f5d00)
[ 1302] gsd-print-notif (struct addr:ffff92939d0f45c0)
[ 1306] gsd-rfkill (struct addr:ffff92939c86ae80)
[ 1308] gsd-screensaver (struct addr:ffff929399601740)
[ 1312] gsd-sharing (struct addr:ffff92939d1c1740)
[ 1314] gsd-smartcard (struct addr:ffff92939bca0000)
[ 1318] gsd-sound (struct addr:ffff929396f48000)
[ 1319] gsd-wacom (struct addr:ffff92939d0f2e80)
[ 1333] ibus-engine-sim (struct addr:ffff92939d1b9740)
[ 1367] colord (struct addr:ffff92939ba51740)
[ 1491] kworker/1:1 (struct addr:ffff92936f0d0000)
[ 1502] kworker/5:0 (struct addr:ffff92936f1e2e80)
[ 1538] kworker/u16:18 (struct addr:ffff92939c1a0000)
[ 1583] irq/127-mei_me (struct addr:ffff9293a41a5d00)
[ 1589] kworker/4:0 (struct addr:ffff9293a2df8000)
[ 1664] kworker/2:2 (struct addr:ffff929369c92e80)
[ 1667] dhclient (struct addr:ffff92939b9f45c0)
[ 1740] gdm-session-wor (struct addr:ffff929369c39740)
[ 1744] systemd (struct addr:ffff929369ce5d00)
[ 1745] (sd-pam) (struct addr:ffff929369d25d00)
[ 1758] gnome-keyring-d (struct addr:ffff929399661740)
[ 1762] gdm-x-session (struct addr:ffff929369d29740)
[ 1764] Xorg (struct addr:ffff92939ba58000)
[ 1769] dbus-daemon (struct addr:ffff929369c38000)
[ 1772] gnome-session-b (struct addr:ffff929369d2dd00)
[ 1869] ssh-agent (struct addr:ffff92939bb81740)
[ 1871] at-spi-bus-laun (struct addr:ffff92939bb85d00)
[ 1876] dbus-daemon (struct addr:ffff9293a40cc5c0)
[ 1878] at-spi2-registr (struct addr:ffff929369c945c0)
[ 1895] gnome-shell (struct addr:ffff929369d3ae80)
[ 1901] gvfsd (struct addr:ffff9293a45add00)
[ 1906] gvfsd-fuse (struct addr:ffff92939bbec5c0)
[ 1917] pulseaudio (struct addr:ffff929369c3dd00)
[ 1934] krfcommd (struct addr:ffff92939ba59740)
[ 1937] ibus-daemon (struct addr:ffff92939a369740)
[ 1941] ibus-dconf (struct addr:ffff92939cd945c0)
[ 1943] ibus-x11 (struct addr:ffff92939bb80000)
[ 1945] ibus-portal (struct addr:ffff92935d5145c0)
[ 1957] gnome-shell-cal (struct addr:ffff92935d4f0000)
[ 1961] evolution-sourc (struct addr:ffff92935d511740)
[ 1971] goa-daemon (struct addr:ffff92935d5e0000)
[ 1978] gvfs-udisks2-vo (struct addr:ffff92935d7045c0)
[ 1987] goa-identity-se (struct addr:ffff92935d660000)
[ 1992] gvfs-goa-volume (struct addr:ffff929369d20000)
[ 1996] gvfs-afc-volume (struct addr:ffff9293a401ae80)
[ 2001] gvfs-mtp-volume (struct addr:ffff92935d705d00)
[ 2005] gvfs-gphoto2-vo (struct addr:ffff92935d5e1740)
[ 2009] gsd-power (struct addr:ffff92936f34dd00)
[ 2010] gsd-print-notif (struct addr:ffff92936f349740)
[ 2012] gsd-rfkill (struct addr:ffff9293996645c0)
[ 2013] gsd-screensaver (struct addr:ffff929358592e80)
[ 2014] gsd-sharing (struct addr:ffff9293585945c0)
[ 2016] gsd-smartcard (struct addr:ffff92935d545d00)
[ 2021] gsd-sound (struct addr:ffff929357d2dd00)
[ 2024] gsd-xsettings (struct addr:ffff929357d8c5c0)
[ 2028] gsd-wacom (struct addr:ffff929357e5dd00)
[ 2041] gsd-a11y-settin (struct addr:ffff929357951740)
[ 2043] gsd-clipboard (struct addr:ffff9293585e5d00)
[ 2044] gsd-color (struct addr:ffff92935858dd00)
[ 2046] gsd-datetime (struct addr:ffff929358589740)
[ 2049] gsd-housekeepin (struct addr:ffff92935798dd00)
[ 2054] gsd-keyboard (struct addr:ffff9293575c5d00)
[ 2055] gsd-media-keys (struct addr:ffff929357671740)
[ 2066] gsd-mouse (struct addr:ffff929358651740)
[ 2103] gsd-disk-utilit (struct addr:ffff929357a65d00)
[ 2109] nautilus-deskto (struct addr:ffff929357a61740)
[ 2117] gsd-printer (struct addr:ffff929357d50000)
[ 2126] gvfsd-trash (struct addr:ffff9293577b2e80)
[ 2144] evolution-calen (struct addr:ffff929357d1dd00)
[ 2148] dconf-service (struct addr:ffff929357c45d00)
[ 2153] ibus-engine-sim (struct addr:ffff929357a62e80)
[ 2164] evolution-calen (struct addr:ffff929357ebae80)
[ 2176] evolution-addre (struct addr:ffff929356c9ae80)
[ 2186] evolution-addre (struct addr:ffff929357ea8000)
[ 2660] gnome-software (struct addr:ffff929339702e80)
[ 2663] update-notifier (struct addr:ffff929357ebdd00)
[ 2669] livepatch-notif (struct addr:ffff929369d3c5c0)
[ 2681] fwupd (struct addr:ffff929348049740)
[ 2784] gnome-terminal- (struct addr:ffff929327af9740)
[ 2794] bash (struct addr:ffff92930a139740)
[ 4034] bash (struct addr:ffff929356c11740)
[ 4244] cupsd (struct addr:ffff92934cca5d00)
[ 4245] cups-browsed (struct addr:ffff9293a06045c0)
[ 4247] dbus (struct addr:ffff9293278add00)
[ 4248] dbus (struct addr:ffff9293278ac5c0)
[ 4362] gnome-calculato (struct addr:ffff929357c40000)
[ 4481] firefox (struct addr:ffff92939d0ac5c0)
[ 4563] Web Content (struct addr:ffff929356c10000)
[ 4626] WebExtensions (struct addr:ffff929357c41740)
[ 4717] Web Content (struct addr:ffff92930a03c5c0)
[ 4770] bash (struct addr:ffff929346065d00)
[ 5192] kworker/3:0 (struct addr:ffff9292c9a5dd00)
[ 7235] sudo (struct addr:ffff9293463c0000)
[ 7236] su (struct addr:ffff92930a355d00)
[ 7237] systemd (struct addr:ffff9292c99aae80)
[ 7238] (sd-pam) (struct addr:ffff9293a3e48000)
[ 7249] bash (struct addr:ffff929348021740)
[ 7318] gedit (struct addr:ffff9293996045c0)
[ 7365] kworker/7:0 (struct addr:ffff9293a41a1740)
[ 7404] Web Content (struct addr:ffff929346061740)
[ 8001] Web Content (struct addr:ffff9292a471dd00)
[ 8053] nautilus (struct addr:ffff9292a6f5c5c0)
[ 8068] mattermost-desk (struct addr:ffff9292a6950000)
[ 8071] mattermost-desk (struct addr:ffff92934817ae80)
[ 8086] gconfd-2 (struct addr:ffff9292a6eb8000)
[ 8107] mattermost-desk (struct addr:ffff9292a558c5c0)
[ 8115] mattermost-desk (struct addr:ffff9292a441ae80)
[ 8197] mattermost-desk (struct addr:ffff9292a6ebc5c0)
[ 8485] kworker/u16:2 (struct addr:ffff9292a5335d00)
[ 8506] ssh-agent (struct addr:ffff929247ee2e80)
[15933] kworker/u16:0 (struct addr:ffff929247ebae80)
[27333] kworker/u16:3 (struct addr:ffff929289c51740)
[29753] bash (struct addr:ffff9292c9a5c5c0)
[31148] kworker/6:2 (struct addr:ffff92930a039740)
[31339] kworker/5:2 (struct addr:ffff9292a4b09740)
[ 4482] kworker/0:0 (struct addr:ffff9292a4548000)
[ 4483] kworker/6:0 (struct addr:ffff9293396fae80)
[ 4557] kworker/2:1 (struct addr:ffff9293396fc5c0)
[ 4558] kworker/7:2 (struct addr:ffff9292a5332e80)
[ 4653] kworker/1:2 (struct addr:ffff929247eb9740)
[ 4698] kworker/3:1 (struct addr:ffff929356c145c0)
[ 4716] kworker/5:1 (struct addr:ffff929289c545c0)
[ 4744] kworker/4:1 (struct addr:ffff929289c52e80)
[ 4745] kworker/0:1 (struct addr:ffff929358590000)
[ 4751] kworker/6:1 (struct addr:ffff9291b44945c0)
[ 4758] kworker/7:1 (struct addr:ffff9293578e5d00)
[ 4763] kworker/1:0 (struct addr:ffff9292a471ae80)
[ 4765] kworker/2:0 (struct addr:ffff929247faae80)
[ 4782] kworker/u16:1 (struct addr:ffff929247fac5c0)
[ 4808] kworker/3:2 (struct addr:ffff9292a4aac5c0)
[ 4841] vmi-process-lis (struct addr:ffff9293396f9740)
```

### CODE REVIEW

**Comment by rianquinn** [comment]
@tklengyel FYI, in the following branch, we have cleaned up the CPUID leaves so use sane values. The leaves that we were using were not in the designated ranges provided by Intel.

**Comment by tklengyel** [comment]
@libvmi-jenkins Retest this please

**Comment by rianquinn** [comment]
The biggest downside is that Intel reserves the leaves we are currently using for future features. They marked off the 0x40000000 + range as never being used specifically so that hypervisors can use it for this exact purpose. This is similar to bit 31 in leaf 1 of ECX which is always marked as never being used by future CPUs specifically so that hypervisors can set that bit to indicate that the OS is in a VM.

**Comment by tklengyel** [comment]
@rianquinn I see minimal risk in highjacking a random cpuid leaf post-boot though.

**Comment by rianquinn** [comment]
Post-boot.... agreed, but Bareflank supports UEFI which is pre-boot

**Comment by tklengyel** [comment]
@smaresca will need a +1 here as I changed the public-facing API to allow passing in multiple types during initialization with `vmi_init_data_t`. This can now be used to pass-in a `memory_map_t` to LibVMI so that it won't touch ranges outside what's marked available. For now this is only required when trying to dump memory through Bareflank as touching MMIO pages is unhealthy and looping from 0 - max_gpfn will do that.

**Comment by Wenzel** [comment]
One Travis test failed:
~~~
The following packages have unmet dependencies:
 libfuse-dev : Depends: libselinux-dev
~~~
But why ?
https://packages.ubuntu.com/trusty/libfuse-dev

**Comment by smaresca** [comment]
+1 looks good to me, have approved

**Pull request merged**
