### PR TITLE
test installation of libvmi in Travis

### PR DESCRIPTION
**Pull request by Wenzel**
Test the installation of libvmi in Travis, as it might fail is something is misconfigured.
I just had a failure with the current version of the repo.

### CODE REVIEW

**Comment by Wenzel** [comment]
Yep, installation fails: https://travis-ci.org/libvmi/libvmi/jobs/491819248#L684
pushing a fix now

**Comment by tklengyel** [comment]
`libvmi.pc` doesn't belong in `${PROJECT_BINARY_DIR}`. It gets installed into the correct location right now.

**Comment by tklengyel** [comment]
Also not sure why you think it fails installation, it installs just fine, even in travis. See https://travis-ci.org/tklengyel/drakvuf/jobs/491432393#L610

**Comment by Wenzel** [comment]
`${PROJECT_BINARY_DIR}/libvmi.pc` is a temporary location before it gets installed.
If i don't put this fix, i have a failure when I install libvmi, look at the previous Travis job:
https://travis-ci.org/libvmi/libvmi/jobs/491819248#L684

**Comment by tklengyel** [comment]
Ah gotcha, as long as the destination doesn't change that's fine.

**Pull request merged**
