### PR TITLE
config: disable unused input and unput lex functions

### PR DESCRIPTION
**Pull request by disaykin**

### CODE REVIEW

**Comment by tklengyel** [comment]
@libvmi-jenkins This is OK to test

**Comment by disaykin** [comment]
The command "sudo -E apt-add-repository -y "ppa:ubuntu-toolchain-r/test"" failed and exited with 1 during .

**Comment by tklengyel** [comment]
@libvmi-jenkins Retest this please

**Comment by tklengyel** [comment]
@libvmi-jenkins Retest this please

**Comment by tklengyel** [comment]
@libvmi-jenkins Retest this please

**Pull request merged**
