### PR TITLE
Bump version to 0.12

### PR DESCRIPTION
**Pull request by tklengyel**

### CODE REVIEW

**Comment by Wenzel** [comment]
I would suggest to bump also the `debian/changelog`.
Btw, what is the `debian/libvmi0.symbols` file ?
the version number `0.11` is everwhere in this one.

**Comment by tklengyel** [comment]
The debian packaging is not really well maintained, `libvmi0.symbols` looks autogenerated but I'm not sure by what.

**Comment by Wenzel** [comment]
I opened an issue for that:
https://github.com/libvmi/libvmi/issues/597

I wanted to track what was needed to get it uploaded to debian mirrors.

**Comment by tklengyel** [comment]
@Wenzel it was git moved, it is no longer in the folder

**Pull request merged**
