### PR TITLE
Set CMake minimum version to 3.1 on Readme

### PR DESCRIPTION
**Pull request by Bondey**

### CODE REVIEW

**Comment by Wenzel** [comment]
There is a macro that checks for the minimum cmake version.

Look at the beginning of the root CMakeLists.txt

**Comment by Wenzel** [comment]
@Bondey , what you should change is this:
https://github.com/libvmi/libvmi/blob/master/CMakeLists.txt#L1

`cmake_minimum_required(VERSION 3.1)`

**Comment by Bondey** [comment]
Sorry, i completely forgot this...

it's done here #741

**Comment by Wenzel** [comment]
@Bondey you have a trailing whitespace:
https://travis-ci.org/libvmi/libvmi/jobs/501588719#L219

We need Travis to go green to merge.

**Comment by Wenzel** [comment]
Help fix #734

**Comment by tklengyel** [comment]
Something is still tripping travis in this PR and can't merge until its fixed

**Comment by Wenzel** [comment]
Yes, there is a trailing whitespace, @Bondey needs to fix it first.

**Pull request closed without merging**
