### PR TITLE
Fix some more coverity bugs

### PR DESCRIPTION
**Pull request by tklengyel**
CID 54271 & CID 54278

### CODE REVIEW

**Comment by tklengyel** [comment]
This is still WIP..

**Comment by tklengyel** [comment]
So basically VMI_CONFIG_STRING can only be used if one inits with VMI_INIT_PARTIAL first and then goes to vmi_init_complete/vmi_init_custom_complete. I'm wondering if we would want to deprecate the config string option to begin with as it has been superseded by the GHashTable method (which is a lot more intuitive IMHO).

**Comment by awsaba** [comment]
I've never liked the way that vmi_instance.image_type was reused (misused?) for VMI_CONFIG_STRING, so I'd be in favor of removing the current implementation.

**Comment by awsaba** [comment]
Is this still WIP?  I say we go ahead and merge it as-is and target removing `VMI_CONFIG_STRING` for the next release.

**Comment by tklengyel** [comment]
It's good to go, let's open an issue for deprecating VMI_CONFIG_STRING.

**Pull request merged**
