### PR TITLE
Fix pyvmi address space

### PR DESCRIPTION
**Pull request by muscatmat**
Most linux plugins were not working due to multiple initialisation of pyvmi

### CODE REVIEW

**Comment by tklengyel** [comment]
So unfortunately pyvmi is currently broken as it has not been kept up-to-date with the API changes. Since there has been work to move the Python 3 in the meanwhile getting the current version of pyvmi fixed was postponed. As for this PR, I don't know whether it makes sense merge. Pinging @smaresca

**Comment by muscatmat** [comment]
The PyVMI utilises the API that LibVMI provides and with this change it interfaces with volatility 2.6 linux plugins which i am currently utilising. I hope this PR is merged with master so others could benefit from utilising PyVMI. If someone has any questions, do not hesitate to contact me.

**Comment by Wenzel** [comment]
hi @muscatmat , i'm working on the new python bindings for libvmi in #532 .
Even thought i have a successfull Rekall vmiaddressspace, I'm struggling with Volatility at the moment.

I saw some of your changes. could you explain a bit what you did and why ?

**Comment by Wenzel** [comment]
@smaresca yes, in the recent #532 merged upstream, i added an updated version of pyvmiaddressspace for Volatility.

**Comment by smaresca** [comment]
closing in light of #532 ; please review the newer CFFI python support and address space. Note: the related address space for rekall was merged upstream, dependent upon @Wenzel's work

**Pull request closed without merging**
