### PR TITLE
remove shm snapshot feature

### PR DESCRIPTION
**Pull request by Wenzel**
Following https://github.com/libvmi/libvmi/pull/674#issuecomment-449757960

deprecate
- `walkthrough_shm_snapshot_pagetable`
- `setup_v2m_table`
- `create_v2m_table`
- `kvm_get_dgvma`

I'm unsure how to proceed at this point, since what we have left is only `kvm_get_dgpma` in the SHM snapshot APIs ?
Should we remove all the SHM snapshot support ?

### CODE REVIEW

**Comment by tklengyel** [comment]
> Should we remove all the SHM snapshot support ?

Yes. It was experimental and is not maintained or even tested - not even compile tested. Anyone still needing it can use the latest release of LibVMI but we should stop carrying that dead code altogether going forward.

**Comment by Wenzel** [comment]
@tklengyel  this PR is ready for review.
Also please note that there was some mention of `shm` in `tools/qemu-kvm-patch/kvm-physmem-access-physmem-snapshot_1.6.0.patch`, not sure what to do with it:

~~~
tools/qemu-kvm-patch/kvm-physmem-access-physmem-snapshot_1.6.0.patch:279:+// shm_pmemsave - same functionality as pmemsave
tools/qemu-kvm-patch/kvm-physmem-access-physmem-snapshot_1.6.0.patch:280:+// except that the "file" is actually shm shared memory space.
tools/qemu-kvm-patch/kvm-physmem-access-physmem-snapshot_1.6.0.patch:281:+int64_t shm_pmemsave(int64_t psize, const char *filename,
tools/qemu-kvm-patch/kvm-physmem-access-physmem-snapshot_1.6.0.patch:284:+    fprintf(stderr, "qemu: shm_pmemsave %s : start\n", filename);
tools/qemu-kvm-patch/kvm-physmem-access-physmem-snapshot_1.6.0.patch:290:+    int shm_fd;
tools/qemu-kvm-patch/kvm-physmem-access-physmem-snapshot_1.6.0.patch:291:+    int shm_flags = O_CREAT | O_RDWR;
tools/qemu-kvm-patch/kvm-physmem-access-physmem-snapshot_1.6.0.patch:293:+    shm_fd = shm_open( filename, shm_flags, (mode_t) perms);
tools/qemu-kvm-patch/kvm-physmem-access-physmem-snapshot_1.6.0.patch:294:+    if ( shm_fd == -1 ) {
tools/qemu-kvm-patch/kvm-physmem-access-physmem-snapshot_1.6.0.patch:300:+    if( ftruncate( shm_fd, size ) == -1 ) {
tools/qemu-kvm-patch/kvm-physmem-access-physmem-snapshot_1.6.0.patch:307:+    uint8_t *shm_buffer;
tools/qemu-kvm-patch/kvm-physmem-access-physmem-snapshot_1.6.0.patch:310:+    shm_buffer = (void *) mmap( NULL, size, mprot, mflags, shm_fd, (off_t)0 );
tools/qemu-kvm-patch/kvm-physmem-access-physmem-snapshot_1.6.0.patch:311:+    if (shm_buffer == MAP_FAILED ) {
tools/qemu-kvm-patch/kvm-physmem-access-physmem-snapshot_1.6.0.patch:326:+        memcpy( (shm_buffer + addr), buf, l );
tools/qemu-kvm-patch/kvm-physmem-access-physmem-snapshot_1.6.0.patch:332:+    // munmap the shm_buffer
tools/qemu-kvm-patch/kvm-physmem-access-physmem-snapshot_1.6.0.patch:333:+    if( munmap( shm_buffer, psize ) == -1 ) {
tools/qemu-kvm-patch/kvm-physmem-access-physmem-snapshot_1.6.0.patch:340:+    close(shm_fd);
tools/qemu-kvm-patch/kvm-physmem-access-physmem-snapshot_1.6.0.patch:352:+    return shm_pmemsave( size, filename, errp );
tools/qemu-kvm-patch/kvm-physmem-access-physmem-snapshot_1.6.0.patch:358:+    shm_unlink( filename );
tools/qemu-kvm-patch/kvm-physmem-access-physmem-snapshot_1.6.0.patch:378:+int64_t shm_pmemsave(int64_t size, const char *filename, Error **errp);
tools/qemu-kvm-patch/kvm-physmem-access-physmem-snapshot_1.6.0.patch:421:+# @filename: store at /dev/shm/filename
tools/qemu-kvm-patch/kvm-physmem-access-physmem-snapshot_1.6.0.patch:435:+# @filename: Destroy snapshot stored at /dev/shm/filename
tools/qemu-kvm-patch/kvm-physmem-access-physmem-snapshot_1.6.0.patch:453:+        .help       = "share guest physical memory image at '/dev/shm/filename'",
tools/qemu-kvm-patch/kvm-physmem-access-physmem-snapshot_1.6.0.patch:479:+        .help       = "destroy guest physical memory image at '/dev/shm/filename'",
~~~

**Comment by tklengyel** [comment]
I wouldn't worry about that KVM patch. We should be replacing the entire KVM driver and deprecating all these patches once there is a solid upstream VMI interface in KVM available.

The PR looks good to me. +1

Pinging @smaresca for another +1

**Comment by smaresca** [comment]
@Wenzel please change the PR title to "remove shm snapshot feature"  -- I consider 'deprecate' to have a different meaning that implies future removal with notice being provided to API users.

I wholeheartedly support removal of the shm snapshot code, though, and I do not think notice is required to downstream library users: This feature has seen very minimal adoption. Maintenance of this feature has caused ample headaches on our end as well.

Just for posterity: I am supportive of the overall intent behind this feature, but I feel strongly that anyone revisiting it would need to implement differently, with emphasis upon driver robustness and transparency for downstream API users.

**Comment by Wenzel** [comment]
@smaresca thanks for your feedback, i changed the title, this PR is ready for merging.

**Pull request merged**
