### PR TITLE
Add cache configuration options to autoconf and remove them from libvmi....

### PR DESCRIPTION
**Pull request by tklengyel**
...h

Now the page cache size can be dynamically configured with ./configure --enable-page-cache=1024 for example.

### CODE REVIEW

**Comment by bdpayne** [comment]
@tklengyel Could you also update the NEWS file for this?

**Comment by tklengyel** [comment]
Sure thing.

**Comment by tklengyel** [comment]
@bdpayne: I think the update should be added in the other open PR to the NEWS file.

**Comment by bdpayne** [comment]
Oh right, I didn't merge that yet ;-)  Ok, I'll cover it.

**Pull request merged**
