### PR TITLE
Add support for Linux KASLR

### LINKED ISSUE #397: Support for Linux KASLR.
I had trouble using libvmi with Linux 4.7.3, as discussed on the libvmi mailing list (https://groups.google.com/forum/#!topic/vmitools/f-LkOKb8bPQ). At least two people seem to have had trouble using libvmi with Linux 4.7.3.

### PR DESCRIPTION
**Pull request by tklengyel**
Fixes #397

### CODE REVIEW

**Comment by tklengyel** [comment]
Retest this please.

**Comment by tklengyel** [comment]
Retest this please.

**Comment by tklengyel** [comment]
Jenkins test-case added and passed: http://libvmitest.zentific.com:8080/job/PR_LibVMI_Xen_Test_Debian_Stretch/1/console

**Comment by smaresca** [comment]
Note: this has now passed a test using our CI system against a system with KASLR enabled. Merging

**Pull request merged**
