### PR TITLE
travis: add test to check release build

### PR DESCRIPTION
**Pull request by Wenzel**
Add a Travis test to check a RELEASE build type in CMake, with restrictive flags like `-Werror`

### CODE REVIEW

**Comment by Wenzel** [comment]
@tklengyel this one is good now

**Comment by tklengyel** [comment]
@libvmi-jenkins This is OK to test

**Comment by tklengyel** [comment]
@libvmi-jenkins Retest this please

**Comment by tklengyel** [comment]
@libvmi-jenkins Retest this please

**Comment by tklengyel** [comment]
@Wenzel Seems to break the test on Jenkins but I don't know why

**Comment by Wenzel** [comment]
`libconfig_parser.so: cannot open shared object file`
I should have done a static linking instead of a dynamic one.
We don't install this library anywhere, that's why.

**Comment by Wenzel** [comment]
@tklengyel all green now o/

**Pull request merged**
