### PR TITLE
More fixes for v0.12 RC

### PR DESCRIPTION
**Pull request by tklengyel**

### CODE REVIEW

**Comment by awsaba** [comment]
retest this please

**Comment by smaresca** [comment]
@bdpayne any updates on the KVM test node? Jenkins is going to spin waiting
for it

**Comment by bdpayne** [comment]
Sorry about that.  I'll look into it today.

**Comment by awsaba** [comment]
Since Xen 4.6 was released last week, I'm going to close this PR and create a new one off of master that includes #263, #285, and maybe #293.

**Pull request closed without merging**
