### PR TITLE
Return canonical VAs in 64-bit get_va_pages

### PR DESCRIPTION
**Pull request by tklengyel**

### CODE REVIEW

**Comment by tklengyel** [comment]
Retest this please

**Comment by tklengyel** [comment]
The ubuntu 64-bit server test VM seems to be down: `libvir: QEMU Driver error : Domain not found: no domain with matching name 'ubuntu-server-1204'`

**Comment by smaresca** [comment]
I'll take a look

**Comment by tklengyel** [comment]
@smaresca: what's the status on the broken PR tester?

Retest this please.

**Comment by tklengyel** [comment]
@bdpayne: is the KVM PR tester still down?

Retest this please.

**Comment by bdpayne** [comment]
@tklengyel Not to my knowledge.  I can dig into this a bit tonight though.

**Comment by tklengyel** [comment]
@bdpayne: thanks, that would be appreciated!

@smaresca: should we try to setup a mirror kvm node in a nested setting on the existing Xen box?

**Comment by bdpayne** [comment]
retest this please

**Comment by bdpayne** [comment]
@tklengyel All fixed.  Sorry that I missed this when you first brought it up.  Looks like the KVM machine was rebooted 15 days ago for some reason.  And the VMs didn't come back up properly.

**Comment by bdpayne** [comment]
Also, +1 on the PR :+1:

**Comment by tklengyel** [comment]
@smaresca or @awsaba: hit merge when you have a minute ;)

**Pull request merged**
