### PR TITLE
Fix compilation with CMAKE_BUILD_TYPE=Release (-Werror)

### PR DESCRIPTION
**Pull request by disaykin**

### CODE REVIEW

**Comment by tklengyel** [comment]
@libvmi-jenkins This is OK to test

**Comment by Wenzel** [comment]
Nice !
Related: #748

**Comment by Wenzel** [comment]
@disaykin  it looks like there are still some compilation errors, at least on Travis setup:
https://travis-ci.org/libvmi/libvmi/jobs/516283005#L389

**Comment by disaykin** [comment]
@wenzel I fix compilattion problems on my system based on Ubuntu 18.04 LTS.

**Comment by disaykin** [comment]
@wenzel This is flex package bug.

**Pull request merged**
