### PR TITLE
Updating qemu-kvm patch for use with libvmi

### PR DESCRIPTION
**Pull request by 0x3430D**
Update tools/qemu_kvm_patch directory with patches for :
- qemu v3.x (compatible with v3.0.0, v3.0.1, v3.1.0, v3.1.1, v3.1.1.1)
- qemu v4.0.0
- qemu v4.1.0

### CODE REVIEW

**Comment by tklengyel** [comment]
@0x3430D Thank you for updating the patchsets. I'm OK with merging this while we wait for normal upstream support to be merged into KVM.

/cc @mtarral thoughts?

**Comment by mtarral** [comment]
I'm also OK with merging this, but I haven't tested them, as I'm focused on KVM-VMI v6.

**Comment by Vladinuto** [comment]
Wouldnt /libvmi/driver/kvm/kvm.c:692 need to be changed too? 

Even if the patch is applied, libvmi fails because it checks for QEMU versions 2.8 or below.

**Comment by engrabdu** [comment]
Just wondering if anyone could help me with updating qemu kvm version from 1.5 to 3.1 on red hat 7.2 with easy steps
thanks

**Pull request merged**
