### PR TITLE
Debian packaging: fix lintian warnings

### PR DESCRIPTION
**Pull request by Wenzel**
Fix warnings and errors in debian packaging.

command: `debuild -us -uc --lintian-opts --profile debian`

There are more fixes to come, but you can already review the existing changes if you wish.
The goal is of course an upload on official Debian repositories.

### CODE REVIEW

**Comment by Wenzel** [comment]
I'm not sure how to fix these:
~~~
W: libvmi source: file-without-copyright-information .astylerc
W: libvmi source: file-without-copyright-information .indent.pro
W: libvmi source: file-without-copyright-information .travis.yml
W: libvmi source: file-without-copyright-information AUTHORS
W: libvmi source: file-without-copyright-information COPYING
W: libvmi source: file-without-copyright-information COPYING.LESSER
W: libvmi source: file-without-copyright-information ChangeLog
W: libvmi source: file-without-copyright-information Makefile.am
W: libvmi source: file-without-copyright-information NEWS
W: libvmi source: file-without-copyright-information README
W: libvmi source: file-without-copyright-information README.rst
W: libvmi source: file-without-copyright-information aclocal.m4
W: libvmi source: file-without-copyright-information autogen.sh
W: libvmi source: file-without-copyright-information config.h.in
W: libvmi source: file-without-copyright-information configure
W: libvmi source: file-without-copyright-information configure.ac
W: libvmi source: file-without-copyright-information doc/doxyfile
W: libvmi source: file-without-copyright-information doc/images/intro-detail.png
W: libvmi source: file-without-copyright-information etc/libvmi-example.conf
W: libvmi source: file-without-copyright-information examples/Makefile.am
W: libvmi source: file-without-copyright-information examples/Makefile.in
W: libvmi source: file-without-copyright-information examples/bug_resume
W: libvmi source: file-without-copyright-information examples/bug_resume.c
W: libvmi source: file-without-copyright-information examples/dump-memory.c
W: libvmi source: file-without-copyright-information examples/event-example.c
W: libvmi source: file-without-copyright-information examples/interrupt-event-example.c
W: libvmi source: file-without-copyright-information examples/map-addr.c
W: libvmi source: file-without-copyright-information examples/map-symbol.c
W: libvmi source: file-without-copyright-information examples/module-list.c
W: libvmi source: file-without-copyright-information examples/msr-event-example.c
W: libvmi source: file-without-copyright-information examples/process-list.c
W: libvmi source: file-without-copyright-information examples/shm-snapshot-process-list.c
W: libvmi source: file-without-copyright-information examples/singlestep-event-example.c
W: libvmi source: file-without-copyright-information examples/step-event-example.c
W: libvmi source: file-without-copyright-information examples/va-pages.c
W: libvmi source: file-without-copyright-information examples/win-guid.c
W: libvmi source: file-without-copyright-information examples/win-guid.h
W: libvmi source: file-without-copyright-information examples/xen-emulate-response.c
W: libvmi source: file-without-copyright-information libvmi.pc.in
W: libvmi source: file-without-copyright-information ltmain.sh
W: libvmi source: file-without-copyright-information m4/libtool.m4
W: libvmi source: file-without-copyright-information m4/ltoptions.m4
W: libvmi source: file-without-copyright-information m4/ltsugar.m4
W: libvmi source: file-without-copyright-information m4/ltversion.m4
W: libvmi source: file-without-copyright-information m4/lt~obsolete.m4
W: libvmi source: file-without-copyright-information notes/embedded-int3.c
W: libvmi source: file-without-copyright-information notes/events.txt
W: libvmi source: file-without-copyright-information notes/freebsd.txt
W: libvmi source: file-without-copyright-information notes/int3-variants-disassembly.txt
W: libvmi source: file-without-copyright-information notes/msr-writes
W: libvmi source: file-without-copyright-information notes/offsets.txt
W: libvmi source: file-without-copyright-information notes/pe.txt
W: libvmi source: file-without-copyright-information notes/winxpsp2-nopae-exports.txt
W: libvmi source: file-without-copyright-information notes/winxpsp2-nopae-offsets.txt
W: libvmi source: file-without-copyright-information notes/winxpsp2-pae-exports.txt
W: libvmi source: file-without-copyright-information notes/winxpsp2-pae-offsets.txt
W: libvmi source: file-without-copyright-information notes/xen-release-dates.txt
W: libvmi source: file-without-copyright-information runindent.py
W: libvmi source: file-without-copyright-information tests/Makefile.am
W: libvmi source: file-without-copyright-information tests/Makefile.in
W: libvmi source: file-without-copyright-information tests/check_runner.c
W: libvmi source: file-without-copyright-information tests/check_tests.h
W: libvmi source: file-without-copyright-information tests/ntkrnlpa.pdb.bd8f451f3e754ed8a34b50560ceb08e31.rekall.json
W: libvmi source: file-without-copyright-information tests/ntoskrnl.pdb.32962337f0f646388b39535cd8dd70e82.rekall.json
W: libvmi source: file-without-copyright-information tests/run_tests.sh
W: libvmi source: file-without-copyright-information tests/test_accessor.c
W: libvmi source: file-without-copyright-information tests/test_cache.c
W: libvmi source: file-without-copyright-information tests/test_getvapages.c
W: libvmi source: file-without-copyright-information tests/test_init.c
W: libvmi source: file-without-copyright-information tests/test_peparse.c
W: libvmi source: file-without-copyright-information tests/test_print.c
W: libvmi source: file-without-copyright-information tests/test_read.c
W: libvmi source: file-without-copyright-information tests/test_shm_snapshot.c
W: libvmi source: file-without-copyright-information tests/test_translate.c
W: libvmi source: file-without-copyright-information tests/test_util.c
W: libvmi source: file-without-copyright-information tests/test_write.c
W: libvmi source: file-without-copyright-information tools/config-editor/README
W: libvmi source: file-without-copyright-information tools/config-editor/config_editor.py
W: libvmi source: file-without-copyright-information tools/linux-offset-finder/Makefile
W: libvmi source: file-without-copyright-information tools/linux-offset-finder/Module.symvers
W: libvmi source: file-without-copyright-information tools/linux-offset-finder/README
W: libvmi source: file-without-copyright-information tools/linux-offset-finder/findoffsets.c
W: libvmi source: file-without-copyright-information tools/performance/Makefile
W: libvmi source: file-without-copyright-information tools/performance/common.c
W: libvmi source: file-without-copyright-information tools/performance/common.h
W: libvmi source: file-without-copyright-information tools/performance/kern_sym.c
W: libvmi source: file-without-copyright-information tools/performance/read_mem.c
W: libvmi source: file-without-copyright-information tools/performance/run-tests.sh
W: libvmi source: file-without-copyright-information tools/performance/user_virt_addr-linux.c
W: libvmi source: file-without-copyright-information tools/performance/user_virt_addr-windows.c
W: libvmi source: file-without-copyright-information tools/performance/virt_addr.c
W: libvmi source: file-without-copyright-information tools/qemu-kvm-patch/README
W: libvmi source: file-without-copyright-information tools/qemu-kvm-patch/kvm-physmem-access-physmem-snapshot_1.6.0.patch
W: libvmi source: file-without-copyright-information tools/qemu-kvm-patch/kvm-physmem-access_0.14.0.patch
W: libvmi source: file-without-copyright-information tools/qemu-kvm-patch/kvm-physmem-access_1.2.0.patch
W: libvmi source: file-without-copyright-information tools/qemu-kvm-patch/kvm-physmem-access_1.5.1.patch
W: libvmi source: file-without-copyright-information tools/qemu-kvm-patch/kvm-qemu-2.4.0.1-libvmi.patch
W: libvmi source: file-without-copyright-information tools/qemu-kvm-patch/kvm-qemu-v2.8-libvmi.patch
W: libvmi source: file-without-copyright-information tools/style/checkpatch.pl
W: libvmi source: file-without-copyright-information tools/vmifs/Makefile.am
W: libvmi source: file-without-copyright-information tools/vmifs/Makefile.in
W: libvmi source: file-without-copyright-information tools/vmifs/vmifs.c
W: libvmi source: file-without-copyright-information tools/windows-offset-finder/README.md
W: libvmi source: file-without-copyright-information tools/windows-offset-finder/createConfig.py
W: libvmi source: file-without-copyright-information tools/windows-offset-finder/downloadPDB.py
W: libvmi source: file-without-copyright-information tools/windows-offset-finder/dumpPDB.py
W: libvmi source: file-without-copyright-information tools/windows-offset-finder/getGUID.cpp
W: libvmi source: file-without-copyright-information tools/windows-offset-finder/rekall_offset_finder.py
~~~
_source-contains-unsafe-symlink_
> The source contains an unsafe symlink. If followed, the link will escape the source root. Note that all absolute symlinks are unconditionally considered "unsafe" in this case (unlike in binary packages).

> If it is a part of the package's testsuite, Lintian may have failed to recognise it as a test. In that case, please override the tag.

**Comment by Wenzel** [comment]
The last one is:
~~~
E: libvmi source: source-contains-unsafe-symlink INSTALL
E: libvmi source: source-contains-unsafe-symlink compile
E: libvmi source: source-contains-unsafe-symlink config.guess
E: libvmi source: source-contains-unsafe-symlink config.sub
E: libvmi source: source-contains-unsafe-symlink depcomp
E: libvmi source: source-contains-unsafe-symlink install-sh
E: libvmi source: source-contains-unsafe-symlink missing
E: libvmi source: source-contains-unsafe-symlink test-driver
E: libvmi source: source-contains-unsafe-symlink ylwrap
~~~
_source-contains-unsafe-symlink_

> The source contains an unsafe symlink. If followed, the link will escape the source root. Note that all absolute symlinks are unconditionally considered "unsafe" in this case (unlike in binary packages).

And, indeed:
~~~
$ ls -l
drwxr-xr-x 2 tarrma tarrma 4,0K mai   21 14:13 autom4te.cache
drwxrwxr-x 7 tarrma tarrma 4,0K mai   21 14:13 debian
drwxrwxr-x 3 tarrma tarrma 4,0K sept.  4  2017 doc
drwxrwxr-x 2 tarrma tarrma 4,0K sept.  4  2017 etc
drwxrwxr-x 3 tarrma tarrma 4,0K mai   21 14:13 examples
drwxrwxr-x 7 tarrma tarrma 4,0K mai   21 14:13 libvmi
drwxr-xr-x 2 tarrma tarrma 4,0K mai   21 14:13 m4
drwxrwxr-x 2 tarrma tarrma 4,0K mai    5 17:43 notes
drwxrwxr-x 2 tarrma tarrma 4,0K mai   21 14:13 tests
drwxrwxr-x 9 tarrma tarrma 4,0K mai    5 17:43 tools
-rw-r--r-- 1 tarrma tarrma  52K mai   21 14:13 aclocal.m4
-rw-rw-r-- 1 tarrma tarrma  395 sept.  4  2017 AUTHORS
-rwxrwxr-x 1 tarrma tarrma  280 sept.  4  2017 autogen.sh
-rw-rw-r-- 1 tarrma tarrma    0 sept.  4  2017 ChangeLog
lrwxrwxrwx 1 tarrma tarrma   32 mai   21 14:13 compile -> /usr/share/automake-1.15/compile
lrwxrwxrwx 1 tarrma tarrma   37 mai   20 15:40 config.guess -> /usr/share/automake-1.15/config.guess
-rw-r--r-- 1 tarrma tarrma 4,1K mai   21 14:13 config.h
-rw-r--r-- 1 tarrma tarrma 3,8K mai   21 14:13 config.h.in
-rw-r--r-- 1 tarrma tarrma  94K mai   21 14:13 config.log
-rwxr-xr-x 1 tarrma tarrma  61K mai   21 14:13 config.status
lrwxrwxrwx 1 tarrma tarrma   35 mai   20 15:40 config.sub -> /usr/share/automake-1.15/config.sub
-rwxr-xr-x 1 tarrma tarrma 486K mai   21 14:13 configure
-rw-rw-r-- 1 tarrma tarrma  13K mai    5 17:43 configure.ac
-rw-rw-r-- 1 tarrma tarrma  35K sept.  4  2017 COPYING
-rw-rw-r-- 1 tarrma tarrma 7,5K sept.  4  2017 COPYING.LESSER
lrwxrwxrwx 1 tarrma tarrma   32 mai   21 14:13 depcomp -> /usr/share/automake-1.15/depcomp
lrwxrwxrwx 1 tarrma tarrma   32 mai   20 15:40 INSTALL -> /usr/share/automake-1.15/INSTALL
lrwxrwxrwx 1 tarrma tarrma   35 mai   20 15:40 install-sh -> /usr/share/automake-1.15/install-sh
-rwxr-xr-x 1 tarrma tarrma 332K mai   21 14:13 libtool
-rw-r--r-- 1 tarrma tarrma  322 mai   21 14:13 libvmi.pc
-rw-rw-r-- 1 tarrma tarrma  258 sept.  4  2017 libvmi.pc.in
-rw-r--r-- 1 tarrma tarrma 317K mai   21 14:13 ltmain.sh
-rw-r--r-- 1 tarrma tarrma  29K mai   21 14:13 Makefile
-rw-rw-r-- 1 tarrma tarrma  296 sept.  4  2017 Makefile.am
-rw-r--r-- 1 tarrma tarrma  28K mai   21 14:13 Makefile.in
lrwxrwxrwx 1 tarrma tarrma   32 mai   21 14:13 missing -> /usr/share/automake-1.15/missing
-rw-rw-r-- 1 tarrma tarrma 5,0K mai    5 17:43 NEWS
-rw-rw-r-- 1 tarrma tarrma   16 sept.  4  2017 README
-rw-rw-r-- 1 tarrma tarrma  13K mai    5 17:43 README.rst
-rwxrwxr-x 1 tarrma tarrma 2,1K sept.  4  2017 runindent.py
-rw-r--r-- 1 tarrma tarrma   23 mai   21 14:13 stamp-h1
lrwxrwxrwx 1 tarrma tarrma   36 mai   20 15:40 test-driver -> /usr/share/automake-1.15/test-driver
lrwxrwxrwx 1 tarrma tarrma   31 mai   20 15:40 ylwrap -> /usr/share/automake-1.15/ylwrap
~~~

Is this a common behavior of automake to generate those symlinks, or we generating them that way ?

**Comment by Wenzel** [comment]
I added the fix for https://github.com/libvmi/libvmi/issues/619.

**Comment by tklengyel** [comment]
Yes, i didn't see any requirement that specifies 0 to be appended to the library name. It makes no sense really.

**Comment by Wenzel** [comment]
From https://www.netfort.gr.jp/~dancer/column/libpkg-guide/libpkg-guide.html#recommendedreading
# 3. Naming shared library packages

The policy documents how to name library packages. `"lib[libraryname][SONAME-version-number]"` like `"libc6"` for `/lib/libc.so.6`

The package name should match the shared library SONAME. It can be deduced with sed s/\.so\./-/ and removing “-” later when removing it will not result in consecutive numbers. Or by using the following code snippet from Steve Langasek. 

~~~
$ objdump -p /path/to/libfoo-bar.so.1.2.3 | \
  sed -n -e's/^[[:space:]]*SONAME[[:space:]]*//p' | \
  sed -e's/\([0-9]\)\.so\./\1-/; s/\.so\.//'
~~~

And if we look at the SONAME:
~~~
$ objdump -p tmp/usr/lib/x86_64-linux-gnu/libvmi.so.0.0.13 | sed -n -e's/^[[:space:]]*SONAME[[:space:]]*//p' | sed -r -e's/([0-9])\.so\./\1-/; s/\.so(\.|$)//; y/_/-/; s/(.*)/\L&/'
libvmi0
~~~

So the package name should be `libvmi0`.
We can work on providing another meta package `libvmi` that will install `libvmi0` maybe.

**Comment by tklengyel** [comment]
@Wenzel `¯\_(ツ)_/¯` feel free to change it back

**Comment by Wenzel** [comment]
@tklengyel done.

I have no clue of how to fix the remaining errors:
~~~
E: libvmi source: source-contains-unsafe-symlink INSTALL
...
~~~

I feel like I need PhD in Debian packaging to reach the standards required by the Debian policies..

**Comment by tklengyel** [comment]
@Wenzel I'm just going to go ahead and merge this as-is and just open an issue to keep track of the remaining task.

**Pull request merged**
