### PR TITLE
Add Travis CI style and compile tests and format code with astyle

### PR DESCRIPTION
**Pull request by tklengyel**
The first commit in this PR applies automatic style adjustments using astyle with the K&R style. The second commit adds the Travis CI config to automatically check new commits for style conformity and compile tests with gcc and clang.

There are no functional changes in this PR to the code, just stylistic.

### CODE REVIEW

**Comment by awsaba** [comment]
:+1:

**Comment by tklengyel** [comment]
Not sure why the Coverity scan is not getting kicked off properly, but it may just be because the PR is coming from a branch outside libvmi/libvmi.

**Comment by rianquinn** [comment]
your setup looks good. I have had this problem in the past, have you tried running coverity scan's build tools manually to see if you can get a build uploaded? It might shed light on the issue.

**Comment by tklengyel** [comment]
@rianquinn it's pretty odd as the same travis syntax worked fine for me on another project, while in here the config says `  "global_env": null,` when it should be `  "global_env": "COVERITY_SCAN_TOKEN=[secure]",`. I'll try a manual build and see if that makes a difference.

**Pull request merged**
