### PR TITLE
Use bddisasm bp emulate example

### PR DESCRIPTION
**Pull request by Wenzel**
Use Bitdefender's [`bddisasm`](https://github.com/bitdefender/bddisasm) library to decode opcodes and emulate them in `breakpoint-emulate-example`

TODO
- [x] handle autotools

### CODE REVIEW

**Review by allewwaly — COMMENTED** [review]
does this breakpoint-emulate-example support Linux? I got the VMI_ERROR message while testing on ubuntu, and the VM crash while I tried to stop the script.
image

And cannot get any events while monitoring fork events, even that I manually called fork in the VM.
image

And failed to set events at certain virtual addresses.
image

**Comment by Wenzel** [comment]
hi @allewwaly 

even though this PR has been opened from KVM-VMI/libvmi, the example cannot be executed under KVM, as the VMI API available is not capable of handling instruction emulation on any kind of events (only pagefault event responses offer to emulate a custom context).
see https://github.com/KVM-VMI/libvmi/issues/39#issue-753577772

the error message is `unhandled event response` which is exactly what's happening.

**Comment by allewwaly** [comment]
is there any working plan on supporting kvm? Any idea on capturing kvm syscalls using libvmi or kvmi-vmi?

**Comment by Wenzel** [comment]
This PR is ready for review.
I will rebase https://github.com/libvmi/libvmi/pull/946 once this one is merged to get autotools support for libbdisasm

**Pull request closed without merging**
