### PR TITLE
Fix artifacts from conversion to 64-bit width vmid 

### PR DESCRIPTION
**Pull request by smaresca**
Miscellaneous fixes: function implementation/prototype matching, function parameters, local variables, format strings.

### CODE REVIEW

**Comment by tklengyel** [comment]
LGTM. What's up with Jenkins though? Seems to be hanging.

**Comment by smaresca** [comment]
looks like the kvm node is down, it's waiting on that

**Comment by bdpayne** [comment]
retest this please

**Comment by bdpayne** [comment]
lgtm

**Pull request merged**
