### PR TITLE
update kvm.c

### PR DESCRIPTION
**Pull request by jie-lin**
Update kvm CPU register parser to support both 32-bit and 64-bit

### CODE REVIEW

**Comment by tklengyel** [comment]
This is OK to test.

**Comment by tklengyel** [comment]
@jie-lin: you don't have to open a new PR each time you update, if you --force push to a branch with an open PR it will automatically update it.

**Comment by tklengyel** [comment]
This is ok to test.

**Comment by jie-lin** [comment]
@tklengyel : OK, thanks

**Comment by tklengyel** [comment]
Thanks, this looks good to me!

**Comment by namidairo** [comment]
I think something may have gone wrong during the force push to his branch, that commit seems to ignore parsing the registers on IA32.

**Comment by tklengyel** [comment]
@namidairo: indeed, should be an easy fix though.

**Pull request merged**
