### PR TITLE
Complete rewrite of python wrapper for LibVMI.

### PR DESCRIPTION
**Pull request by bdpayne**
PyVMI is built around CFFI, which provides a much cleaner interface between
the C and python code bases.  This includes a libvmi modules that directly
exposes much of the libvmi functionality.  This also includes a pyvmi module
that is more pythonic, allowing for nicer looking python introspection code.
See the example to understand the benefits.

Also updated the volatility address space to work with the new PyVMI.

Finally, this includes a test suite that will run through some basic sanity
checking.  Currently this is hard coded to expect a winxpsp2 VM.  This can
be generalized in the future to allow for broader testing.

### CODE REVIEW

**Comment by awsaba** [comment]
@bdpayne what's the current prognosis for this?  Would it address #299?

**Comment by bdpayne** [comment]
Unfortunately, this br.anch probably needs a fair bit of work.  I would still love to see us go in this direction, but I haven't had the cycles to pursue this in a while.  I went ahead and merged the other PR as it makes the current pyvmi solution better (fixes legit bugs) and seems like a good thing to have in place until this is ready.

**Comment by smaresca** [comment]
@bdpayne I'm going to run with this one and bring it up to speed if you don't mind

**Comment by bdpayne** [comment]
@smaresca Works with me!

**Comment by Wenzel** [comment]
up !
@bdpayne are you still working on this ?

**Comment by smaresca** [comment]
@Wenzel not anymore - @bdpayne is no longer working on this

**Comment by smaresca** [comment]
closing in light of the work done by @Wenzel

**Pull request closed without merging**
